//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace placementDepartmentDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coordinating_jobs_for_graduates
    {
        public int Id { get; set; }
        public System.DateTime dateReceived { get; set; }
        public Nullable<System.DateTime> lastUpdateDate { get; set; }
    
        public virtual Graduate Graduate { get; set; }
        public virtual Job Job { get; set; }
        public virtual Job_coordination_status Job_coordination_status { get; set; }
    }
}
