//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace placementDepartmentDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Graduate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Graduate()
        {
            this.Coordinating_jobs_for_graduates = new HashSet<Coordinating_jobs_for_graduates>();
            this.Graduate_languages = new HashSet<Graduate_languages>();
        }
    
        public string Id { get; set; }
        public string gender { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public string address { get; set; }
        public string zipCode { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string startYear { get; set; }
        public string endYear { get; set; }
        public System.DateTime dateOfRegistration { get; set; }
        public System.DateTime lastUpdate { get; set; }
        public bool didGraduate { get; set; }
        public bool hasDiploma { get; set; }
        public bool isWorkerInProfession { get; set; }
        public string companyName { get; set; }
        public string role { get; set; }
        public Nullable<bool> placedByThePlacementDepartment { get; set; }
        public bool hasExperience { get; set; }
        public bool isActive { get; set; }
        public string linkToCV { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coordinating_jobs_for_graduates> Coordinating_jobs_for_graduates { get; set; }
        public virtual Expertise Expertise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Graduate_languages> Graduate_languages { get; set; }
    }
}
