//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace placementDepartmentDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Graduate_languages
    {
        public string graduateId { get; set; }
        public int languageId { get; set; }
        public Nullable<int> level { get; set; }
    
        public virtual Graduate Graduate { get; set; }
        public virtual Language Language { get; set; }
    }
}
