//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace placementDepartmentDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.CoordinatingJobsForGraduates = new HashSet<CoordinatingJobsForGraduates>();
        }
    
        public int Id { get; set; }
        public System.DateTime dateReceived { get; set; }
        public Nullable<int> gettingId { get; set; }
        public int handlesId { get; set; }
        public int contactId { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int subjectId { get; set; }
        public bool isActive { get; set; }
        public Nullable<int> reasonForClosing { get; set; }
        public bool didSendCV { get; set; }
        public System.DateTime lastUpdateDate { get; set; }
    
        public virtual Contact Contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoordinatingJobsForGraduates> CoordinatingJobsForGraduates { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ReasonForClosingThePosition ReasonForClosingThePosition { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
