//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace placementDepartmentDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class placementDepartmentDBEntities : DbContext
    {
        public placementDepartmentDBEntities()
            : base("name=placementDepartmentDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branch { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<CoordinatingJobsForGraduates> CoordinatingJobsForGraduates { get; set; }
        public virtual DbSet<Expertise> Expertise { get; set; }
        public virtual DbSet<Graduate> Graduate { get; set; }
        public virtual DbSet<GraduateLanguages> GraduateLanguages { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<JobCoordinationStatus> JobCoordinationStatus { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<Permission> Permission { get; set; }
        public virtual DbSet<ReasonForClosingThePosition> ReasonForClosingThePosition { get; set; }
        public virtual DbSet<Reminder> Reminder { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
